### PR TITLE
Added 2 solutions for 069_Sqrt(x)

### PR DESCRIPTION
**Pull request by MichaelRomani**

### CODE REVIEW

**Review by erenerdo — APPROVED** [review]
this is fresh af

**Comment by kyusulamita** [comment]
WHY HAVEN"T YOU UPDATED THE README

**Comment by kyusulamita** [comment]
Eren is going to get his admin privileges taken awayy
wahhhh

**Comment by kyusulamita** [comment]
I'm tired and sleepy

**Comment by kyusulamita** [comment]
send halp

**Pull request merged**
